.TH FREEGISH 6 "Dec  25, 2010"
.SH NAME
freegish \- A physics based arcade game
.SH SYNOPSIS
.B freegish
.RI [ options ]
.SH DESCRIPTION
\fBfreegish\fP is a physics based arcade game
.SH OPTIONS
.TP
.B \-nosound
Disable sound and music
.TP
.B \-sound
Enable sound
.TP
.B \-nomusic
Disable  music
.SH FILES
\fI${HOME}/.freegish/level/\fR - directory containing custom levels
.SH AUTHOR
Gish was written by Cryptic Sea and FreeGish is maintained by FreeGish team.
.PP
This manual page was written by Lubos Novak <alvinx12@centrum.cz>,
for the Debian project (and may be used by others).
