# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bob/projects/gish

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bob/projects/gish

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bob/projects/gish/CMakeFiles /home/bob/projects/gish/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bob/projects/gish/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gish

# Build rule for target.
gish: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gish
.PHONY : gish

# fast build rule for target.
gish/fast:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/build
.PHONY : gish/fast

audio/audio.o: audio/audio.c.o
.PHONY : audio/audio.o

# target to build an object file
audio/audio.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/audio/audio.c.o
.PHONY : audio/audio.c.o

audio/audio.i: audio/audio.c.i
.PHONY : audio/audio.i

# target to preprocess a source file
audio/audio.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/audio/audio.c.i
.PHONY : audio/audio.c.i

audio/audio.s: audio/audio.c.s
.PHONY : audio/audio.s

# target to generate assembly for a file
audio/audio.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/audio/audio.c.s
.PHONY : audio/audio.c.s

game/ai.o: game/ai.c.o
.PHONY : game/ai.o

# target to build an object file
game/ai.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/ai.c.o
.PHONY : game/ai.c.o

game/ai.i: game/ai.c.i
.PHONY : game/ai.i

# target to preprocess a source file
game/ai.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/ai.c.i
.PHONY : game/ai.c.i

game/ai.s: game/ai.c.s
.PHONY : game/ai.s

# target to generate assembly for a file
game/ai.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/ai.c.s
.PHONY : game/ai.c.s

game/animation.o: game/animation.c.o
.PHONY : game/animation.o

# target to build an object file
game/animation.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/animation.c.o
.PHONY : game/animation.c.o

game/animation.i: game/animation.c.i
.PHONY : game/animation.i

# target to preprocess a source file
game/animation.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/animation.c.i
.PHONY : game/animation.c.i

game/animation.s: game/animation.c.s
.PHONY : game/animation.s

# target to generate assembly for a file
game/animation.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/animation.c.s
.PHONY : game/animation.c.s

game/block.o: game/block.c.o
.PHONY : game/block.o

# target to build an object file
game/block.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/block.c.o
.PHONY : game/block.c.o

game/block.i: game/block.c.i
.PHONY : game/block.i

# target to preprocess a source file
game/block.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/block.c.i
.PHONY : game/block.c.i

game/block.s: game/block.c.s
.PHONY : game/block.s

# target to generate assembly for a file
game/block.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/block.c.s
.PHONY : game/block.c.s

game/boss.o: game/boss.c.o
.PHONY : game/boss.o

# target to build an object file
game/boss.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/boss.c.o
.PHONY : game/boss.c.o

game/boss.i: game/boss.c.i
.PHONY : game/boss.i

# target to preprocess a source file
game/boss.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/boss.c.i
.PHONY : game/boss.c.i

game/boss.s: game/boss.c.s
.PHONY : game/boss.s

# target to generate assembly for a file
game/boss.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/boss.c.s
.PHONY : game/boss.c.s

game/config.o: game/config.c.o
.PHONY : game/config.o

# target to build an object file
game/config.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/config.c.o
.PHONY : game/config.c.o

game/config.i: game/config.c.i
.PHONY : game/config.i

# target to preprocess a source file
game/config.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/config.c.i
.PHONY : game/config.c.i

game/config.s: game/config.c.s
.PHONY : game/config.s

# target to generate assembly for a file
game/config.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/config.c.s
.PHONY : game/config.c.s

game/credits.o: game/credits.c.o
.PHONY : game/credits.o

# target to build an object file
game/credits.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/credits.c.o
.PHONY : game/credits.c.o

game/credits.i: game/credits.c.i
.PHONY : game/credits.i

# target to preprocess a source file
game/credits.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/credits.c.i
.PHONY : game/credits.c.i

game/credits.s: game/credits.c.s
.PHONY : game/credits.s

# target to generate assembly for a file
game/credits.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/credits.c.s
.PHONY : game/credits.c.s

game/custom.o: game/custom.c.o
.PHONY : game/custom.o

# target to build an object file
game/custom.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/custom.c.o
.PHONY : game/custom.c.o

game/custom.i: game/custom.c.i
.PHONY : game/custom.i

# target to preprocess a source file
game/custom.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/custom.c.i
.PHONY : game/custom.c.i

game/custom.s: game/custom.c.s
.PHONY : game/custom.s

# target to generate assembly for a file
game/custom.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/custom.c.s
.PHONY : game/custom.c.s

game/damage.o: game/damage.c.o
.PHONY : game/damage.o

# target to build an object file
game/damage.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/damage.c.o
.PHONY : game/damage.c.o

game/damage.i: game/damage.c.i
.PHONY : game/damage.i

# target to preprocess a source file
game/damage.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/damage.c.i
.PHONY : game/damage.c.i

game/damage.s: game/damage.c.s
.PHONY : game/damage.s

# target to generate assembly for a file
game/damage.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/damage.c.s
.PHONY : game/damage.c.s

game/debug.o: game/debug.c.o
.PHONY : game/debug.o

# target to build an object file
game/debug.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/debug.c.o
.PHONY : game/debug.c.o

game/debug.i: game/debug.c.i
.PHONY : game/debug.i

# target to preprocess a source file
game/debug.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/debug.c.i
.PHONY : game/debug.c.i

game/debug.s: game/debug.c.s
.PHONY : game/debug.s

# target to generate assembly for a file
game/debug.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/debug.c.s
.PHONY : game/debug.c.s

game/editor.o: game/editor.c.o
.PHONY : game/editor.o

# target to build an object file
game/editor.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/editor.c.o
.PHONY : game/editor.c.o

game/editor.i: game/editor.c.i
.PHONY : game/editor.i

# target to preprocess a source file
game/editor.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/editor.c.i
.PHONY : game/editor.c.i

game/editor.s: game/editor.c.s
.PHONY : game/editor.s

# target to generate assembly for a file
game/editor.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/editor.c.s
.PHONY : game/editor.c.s

game/game.o: game/game.c.o
.PHONY : game/game.o

# target to build an object file
game/game.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/game.c.o
.PHONY : game/game.c.o

game/game.i: game/game.c.i
.PHONY : game/game.i

# target to preprocess a source file
game/game.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/game.c.i
.PHONY : game/game.c.i

game/game.s: game/game.c.s
.PHONY : game/game.s

# target to generate assembly for a file
game/game.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/game.c.s
.PHONY : game/game.c.s

game/gameaudio.o: game/gameaudio.c.o
.PHONY : game/gameaudio.o

# target to build an object file
game/gameaudio.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/gameaudio.c.o
.PHONY : game/gameaudio.c.o

game/gameaudio.i: game/gameaudio.c.i
.PHONY : game/gameaudio.i

# target to preprocess a source file
game/gameaudio.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/gameaudio.c.i
.PHONY : game/gameaudio.c.i

game/gameaudio.s: game/gameaudio.c.s
.PHONY : game/gameaudio.s

# target to generate assembly for a file
game/gameaudio.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/gameaudio.c.s
.PHONY : game/gameaudio.c.s

game/gamemenu.o: game/gamemenu.c.o
.PHONY : game/gamemenu.o

# target to build an object file
game/gamemenu.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/gamemenu.c.o
.PHONY : game/gamemenu.c.o

game/gamemenu.i: game/gamemenu.c.i
.PHONY : game/gamemenu.i

# target to preprocess a source file
game/gamemenu.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/gamemenu.c.i
.PHONY : game/gamemenu.c.i

game/gamemenu.s: game/gamemenu.c.s
.PHONY : game/gamemenu.s

# target to generate assembly for a file
game/gamemenu.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/gamemenu.c.s
.PHONY : game/gamemenu.c.s

game/gameobject.o: game/gameobject.c.o
.PHONY : game/gameobject.o

# target to build an object file
game/gameobject.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/gameobject.c.o
.PHONY : game/gameobject.c.o

game/gameobject.i: game/gameobject.c.i
.PHONY : game/gameobject.i

# target to preprocess a source file
game/gameobject.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/gameobject.c.i
.PHONY : game/gameobject.c.i

game/gameobject.s: game/gameobject.c.s
.PHONY : game/gameobject.s

# target to generate assembly for a file
game/gameobject.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/gameobject.c.s
.PHONY : game/gameobject.c.s

game/gametexture.o: game/gametexture.c.o
.PHONY : game/gametexture.o

# target to build an object file
game/gametexture.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/gametexture.c.o
.PHONY : game/gametexture.c.o

game/gametexture.i: game/gametexture.c.i
.PHONY : game/gametexture.i

# target to preprocess a source file
game/gametexture.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/gametexture.c.i
.PHONY : game/gametexture.c.i

game/gametexture.s: game/gametexture.c.s
.PHONY : game/gametexture.s

# target to generate assembly for a file
game/gametexture.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/gametexture.c.s
.PHONY : game/gametexture.c.s

game/high.o: game/high.c.o
.PHONY : game/high.o

# target to build an object file
game/high.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/high.c.o
.PHONY : game/high.c.o

game/high.i: game/high.c.i
.PHONY : game/high.i

# target to preprocess a source file
game/high.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/high.c.i
.PHONY : game/high.c.i

game/high.s: game/high.c.s
.PHONY : game/high.s

# target to generate assembly for a file
game/high.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/high.c.s
.PHONY : game/high.c.s

game/level.o: game/level.c.o
.PHONY : game/level.o

# target to build an object file
game/level.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/level.c.o
.PHONY : game/level.c.o

game/level.i: game/level.c.i
.PHONY : game/level.i

# target to preprocess a source file
game/level.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/level.c.i
.PHONY : game/level.c.i

game/level.s: game/level.c.s
.PHONY : game/level.s

# target to generate assembly for a file
game/level.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/level.c.s
.PHONY : game/level.c.s

game/lighting.o: game/lighting.c.o
.PHONY : game/lighting.o

# target to build an object file
game/lighting.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/lighting.c.o
.PHONY : game/lighting.c.o

game/lighting.i: game/lighting.c.i
.PHONY : game/lighting.i

# target to preprocess a source file
game/lighting.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/lighting.c.i
.PHONY : game/lighting.c.i

game/lighting.s: game/lighting.c.s
.PHONY : game/lighting.s

# target to generate assembly for a file
game/lighting.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/lighting.c.s
.PHONY : game/lighting.c.s

game/logic.o: game/logic.c.o
.PHONY : game/logic.o

# target to build an object file
game/logic.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/logic.c.o
.PHONY : game/logic.c.o

game/logic.i: game/logic.c.i
.PHONY : game/logic.i

# target to preprocess a source file
game/logic.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/logic.c.i
.PHONY : game/logic.c.i

game/logic.s: game/logic.c.s
.PHONY : game/logic.s

# target to generate assembly for a file
game/logic.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/logic.c.s
.PHONY : game/logic.c.s

game/mainmenu.o: game/mainmenu.c.o
.PHONY : game/mainmenu.o

# target to build an object file
game/mainmenu.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/mainmenu.c.o
.PHONY : game/mainmenu.c.o

game/mainmenu.i: game/mainmenu.c.i
.PHONY : game/mainmenu.i

# target to preprocess a source file
game/mainmenu.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/mainmenu.c.i
.PHONY : game/mainmenu.c.i

game/mainmenu.s: game/mainmenu.c.s
.PHONY : game/mainmenu.s

# target to generate assembly for a file
game/mainmenu.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/mainmenu.c.s
.PHONY : game/mainmenu.c.s

game/mappack.o: game/mappack.c.o
.PHONY : game/mappack.o

# target to build an object file
game/mappack.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/mappack.c.o
.PHONY : game/mappack.c.o

game/mappack.i: game/mappack.c.i
.PHONY : game/mappack.i

# target to preprocess a source file
game/mappack.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/mappack.c.i
.PHONY : game/mappack.c.i

game/mappack.s: game/mappack.c.s
.PHONY : game/mappack.s

# target to generate assembly for a file
game/mappack.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/mappack.c.s
.PHONY : game/mappack.c.s

game/music.o: game/music.c.o
.PHONY : game/music.o

# target to build an object file
game/music.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/music.c.o
.PHONY : game/music.c.o

game/music.i: game/music.c.i
.PHONY : game/music.i

# target to preprocess a source file
game/music.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/music.c.i
.PHONY : game/music.c.i

game/music.s: game/music.c.s
.PHONY : game/music.s

# target to generate assembly for a file
game/music.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/music.c.s
.PHONY : game/music.c.s

game/objedit.o: game/objedit.c.o
.PHONY : game/objedit.o

# target to build an object file
game/objedit.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/objedit.c.o
.PHONY : game/objedit.c.o

game/objedit.i: game/objedit.c.i
.PHONY : game/objedit.i

# target to preprocess a source file
game/objedit.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/objedit.c.i
.PHONY : game/objedit.c.i

game/objedit.s: game/objedit.c.s
.PHONY : game/objedit.s

# target to generate assembly for a file
game/objedit.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/objedit.c.s
.PHONY : game/objedit.c.s

game/objfunc.o: game/objfunc.c.o
.PHONY : game/objfunc.o

# target to build an object file
game/objfunc.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/objfunc.c.o
.PHONY : game/objfunc.c.o

game/objfunc.i: game/objfunc.c.i
.PHONY : game/objfunc.i

# target to preprocess a source file
game/objfunc.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/objfunc.c.i
.PHONY : game/objfunc.c.i

game/objfunc.s: game/objfunc.c.s
.PHONY : game/objfunc.s

# target to generate assembly for a file
game/objfunc.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/objfunc.c.s
.PHONY : game/objfunc.c.s

game/options.o: game/options.c.o
.PHONY : game/options.o

# target to build an object file
game/options.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/options.c.o
.PHONY : game/options.c.o

game/options.i: game/options.c.i
.PHONY : game/options.i

# target to preprocess a source file
game/options.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/options.c.i
.PHONY : game/options.c.i

game/options.s: game/options.c.s
.PHONY : game/options.s

# target to generate assembly for a file
game/options.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/options.c.s
.PHONY : game/options.c.s

game/physics.o: game/physics.c.o
.PHONY : game/physics.o

# target to build an object file
game/physics.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/physics.c.o
.PHONY : game/physics.c.o

game/physics.i: game/physics.c.i
.PHONY : game/physics.i

# target to preprocess a source file
game/physics.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/physics.c.i
.PHONY : game/physics.c.i

game/physics.s: game/physics.c.s
.PHONY : game/physics.s

# target to generate assembly for a file
game/physics.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/physics.c.s
.PHONY : game/physics.c.s

game/player.o: game/player.c.o
.PHONY : game/player.o

# target to build an object file
game/player.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/player.c.o
.PHONY : game/player.c.o

game/player.i: game/player.c.i
.PHONY : game/player.i

# target to preprocess a source file
game/player.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/player.c.i
.PHONY : game/player.c.i

game/player.s: game/player.c.s
.PHONY : game/player.s

# target to generate assembly for a file
game/player.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/player.c.s
.PHONY : game/player.c.s

game/prerender.o: game/prerender.c.o
.PHONY : game/prerender.o

# target to build an object file
game/prerender.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/prerender.c.o
.PHONY : game/prerender.c.o

game/prerender.i: game/prerender.c.i
.PHONY : game/prerender.i

# target to preprocess a source file
game/prerender.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/prerender.c.i
.PHONY : game/prerender.c.i

game/prerender.s: game/prerender.c.s
.PHONY : game/prerender.s

# target to generate assembly for a file
game/prerender.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/prerender.c.s
.PHONY : game/prerender.c.s

game/random.o: game/random.c.o
.PHONY : game/random.o

# target to build an object file
game/random.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/random.c.o
.PHONY : game/random.c.o

game/random.i: game/random.c.i
.PHONY : game/random.i

# target to preprocess a source file
game/random.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/random.c.i
.PHONY : game/random.c.i

game/random.s: game/random.c.s
.PHONY : game/random.s

# target to generate assembly for a file
game/random.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/random.c.s
.PHONY : game/random.c.s

game/record.o: game/record.c.o
.PHONY : game/record.o

# target to build an object file
game/record.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/record.c.o
.PHONY : game/record.c.o

game/record.i: game/record.c.i
.PHONY : game/record.i

# target to preprocess a source file
game/record.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/record.c.i
.PHONY : game/record.c.i

game/record.s: game/record.c.s
.PHONY : game/record.s

# target to generate assembly for a file
game/record.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/record.c.s
.PHONY : game/record.c.s

game/render.o: game/render.c.o
.PHONY : game/render.o

# target to build an object file
game/render.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/render.c.o
.PHONY : game/render.c.o

game/render.i: game/render.c.i
.PHONY : game/render.i

# target to preprocess a source file
game/render.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/render.c.i
.PHONY : game/render.c.i

game/render.s: game/render.c.s
.PHONY : game/render.s

# target to generate assembly for a file
game/render.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/render.c.s
.PHONY : game/render.c.s

game/replay.o: game/replay.c.o
.PHONY : game/replay.o

# target to build an object file
game/replay.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/replay.c.o
.PHONY : game/replay.c.o

game/replay.i: game/replay.c.i
.PHONY : game/replay.i

# target to preprocess a source file
game/replay.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/replay.c.i
.PHONY : game/replay.c.i

game/replay.s: game/replay.c.s
.PHONY : game/replay.s

# target to generate assembly for a file
game/replay.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/replay.c.s
.PHONY : game/replay.c.s

game/ropeedit.o: game/ropeedit.c.o
.PHONY : game/ropeedit.o

# target to build an object file
game/ropeedit.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/ropeedit.c.o
.PHONY : game/ropeedit.c.o

game/ropeedit.i: game/ropeedit.c.i
.PHONY : game/ropeedit.i

# target to preprocess a source file
game/ropeedit.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/ropeedit.c.i
.PHONY : game/ropeedit.c.i

game/ropeedit.s: game/ropeedit.c.s
.PHONY : game/ropeedit.s

# target to generate assembly for a file
game/ropeedit.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/ropeedit.c.s
.PHONY : game/ropeedit.c.s

game/setup.o: game/setup.c.o
.PHONY : game/setup.o

# target to build an object file
game/setup.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/setup.c.o
.PHONY : game/setup.c.o

game/setup.i: game/setup.c.i
.PHONY : game/setup.i

# target to preprocess a source file
game/setup.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/setup.c.i
.PHONY : game/setup.c.i

game/setup.s: game/setup.c.s
.PHONY : game/setup.s

# target to generate assembly for a file
game/setup.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/setup.c.s
.PHONY : game/setup.c.s

game/socket.o: game/socket.c.o
.PHONY : game/socket.o

# target to build an object file
game/socket.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/socket.c.o
.PHONY : game/socket.c.o

game/socket.i: game/socket.c.i
.PHONY : game/socket.i

# target to preprocess a source file
game/socket.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/socket.c.i
.PHONY : game/socket.c.i

game/socket.s: game/socket.c.s
.PHONY : game/socket.s

# target to generate assembly for a file
game/socket.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/socket.c.s
.PHONY : game/socket.c.s

game/sprite.o: game/sprite.c.o
.PHONY : game/sprite.o

# target to build an object file
game/sprite.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/sprite.c.o
.PHONY : game/sprite.c.o

game/sprite.i: game/sprite.c.i
.PHONY : game/sprite.i

# target to preprocess a source file
game/sprite.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/sprite.c.i
.PHONY : game/sprite.c.i

game/sprite.s: game/sprite.c.s
.PHONY : game/sprite.s

# target to generate assembly for a file
game/sprite.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/sprite.c.s
.PHONY : game/sprite.c.s

game/vsmode.o: game/vsmode.c.o
.PHONY : game/vsmode.o

# target to build an object file
game/vsmode.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/vsmode.c.o
.PHONY : game/vsmode.c.o

game/vsmode.i: game/vsmode.c.i
.PHONY : game/vsmode.i

# target to preprocess a source file
game/vsmode.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/vsmode.c.i
.PHONY : game/vsmode.c.i

game/vsmode.s: game/vsmode.c.s
.PHONY : game/vsmode.s

# target to generate assembly for a file
game/vsmode.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/game/vsmode.c.s
.PHONY : game/vsmode.c.s

input/joystick.o: input/joystick.c.o
.PHONY : input/joystick.o

# target to build an object file
input/joystick.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/input/joystick.c.o
.PHONY : input/joystick.c.o

input/joystick.i: input/joystick.c.i
.PHONY : input/joystick.i

# target to preprocess a source file
input/joystick.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/input/joystick.c.i
.PHONY : input/joystick.c.i

input/joystick.s: input/joystick.c.s
.PHONY : input/joystick.s

# target to generate assembly for a file
input/joystick.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/input/joystick.c.s
.PHONY : input/joystick.c.s

input/keyboard.o: input/keyboard.c.o
.PHONY : input/keyboard.o

# target to build an object file
input/keyboard.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/input/keyboard.c.o
.PHONY : input/keyboard.c.o

input/keyboard.i: input/keyboard.c.i
.PHONY : input/keyboard.i

# target to preprocess a source file
input/keyboard.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/input/keyboard.c.i
.PHONY : input/keyboard.c.i

input/keyboard.s: input/keyboard.c.s
.PHONY : input/keyboard.s

# target to generate assembly for a file
input/keyboard.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/input/keyboard.c.s
.PHONY : input/keyboard.c.s

input/mouse.o: input/mouse.c.o
.PHONY : input/mouse.o

# target to build an object file
input/mouse.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/input/mouse.c.o
.PHONY : input/mouse.c.o

input/mouse.i: input/mouse.c.i
.PHONY : input/mouse.i

# target to preprocess a source file
input/mouse.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/input/mouse.c.i
.PHONY : input/mouse.c.i

input/mouse.s: input/mouse.c.s
.PHONY : input/mouse.s

# target to generate assembly for a file
input/mouse.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/input/mouse.c.s
.PHONY : input/mouse.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/main.c.s
.PHONY : main.c.s

math/intersec.o: math/intersec.c.o
.PHONY : math/intersec.o

# target to build an object file
math/intersec.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/math/intersec.c.o
.PHONY : math/intersec.c.o

math/intersec.i: math/intersec.c.i
.PHONY : math/intersec.i

# target to preprocess a source file
math/intersec.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/math/intersec.c.i
.PHONY : math/intersec.c.i

math/intersec.s: math/intersec.c.s
.PHONY : math/intersec.s

# target to generate assembly for a file
math/intersec.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/math/intersec.c.s
.PHONY : math/intersec.c.s

math/vector.o: math/vector.c.o
.PHONY : math/vector.o

# target to build an object file
math/vector.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/math/vector.c.o
.PHONY : math/vector.c.o

math/vector.i: math/vector.c.i
.PHONY : math/vector.i

# target to preprocess a source file
math/vector.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/math/vector.c.i
.PHONY : math/vector.c.i

math/vector.s: math/vector.c.s
.PHONY : math/vector.s

# target to generate assembly for a file
math/vector.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/math/vector.c.s
.PHONY : math/vector.c.s

menu/menu.o: menu/menu.c.o
.PHONY : menu/menu.o

# target to build an object file
menu/menu.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/menu/menu.c.o
.PHONY : menu/menu.c.o

menu/menu.i: menu/menu.c.i
.PHONY : menu/menu.i

# target to preprocess a source file
menu/menu.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/menu/menu.c.i
.PHONY : menu/menu.c.i

menu/menu.s: menu/menu.c.s
.PHONY : menu/menu.s

# target to generate assembly for a file
menu/menu.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/menu/menu.c.s
.PHONY : menu/menu.c.s

parser/parser.o: parser/parser.c.o
.PHONY : parser/parser.o

# target to build an object file
parser/parser.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/parser/parser.c.o
.PHONY : parser/parser.c.o

parser/parser.i: parser/parser.c.i
.PHONY : parser/parser.i

# target to preprocess a source file
parser/parser.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/parser/parser.c.i
.PHONY : parser/parser.c.i

parser/parser.s: parser/parser.c.s
.PHONY : parser/parser.s

# target to generate assembly for a file
parser/parser.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/parser/parser.c.s
.PHONY : parser/parser.c.s

physics/bond.o: physics/bond.c.o
.PHONY : physics/bond.o

# target to build an object file
physics/bond.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/physics/bond.c.o
.PHONY : physics/bond.c.o

physics/bond.i: physics/bond.c.i
.PHONY : physics/bond.i

# target to preprocess a source file
physics/bond.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/physics/bond.c.i
.PHONY : physics/bond.c.i

physics/bond.s: physics/bond.c.s
.PHONY : physics/bond.s

# target to generate assembly for a file
physics/bond.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/physics/bond.c.s
.PHONY : physics/bond.c.s

physics/object.o: physics/object.c.o
.PHONY : physics/object.o

# target to build an object file
physics/object.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/physics/object.c.o
.PHONY : physics/object.c.o

physics/object.i: physics/object.c.i
.PHONY : physics/object.i

# target to preprocess a source file
physics/object.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/physics/object.c.i
.PHONY : physics/object.c.i

physics/object.s: physics/object.c.s
.PHONY : physics/object.s

# target to generate assembly for a file
physics/object.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/physics/object.c.s
.PHONY : physics/object.c.s

physics/particle.o: physics/particle.c.o
.PHONY : physics/particle.o

# target to build an object file
physics/particle.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/physics/particle.c.o
.PHONY : physics/particle.c.o

physics/particle.i: physics/particle.c.i
.PHONY : physics/particle.i

# target to preprocess a source file
physics/particle.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/physics/particle.c.i
.PHONY : physics/particle.c.i

physics/particle.s: physics/particle.c.s
.PHONY : physics/particle.s

# target to generate assembly for a file
physics/particle.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/physics/particle.c.s
.PHONY : physics/particle.c.s

sdl/endian.o: sdl/endian.c.o
.PHONY : sdl/endian.o

# target to build an object file
sdl/endian.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/sdl/endian.c.o
.PHONY : sdl/endian.c.o

sdl/endian.i: sdl/endian.c.i
.PHONY : sdl/endian.i

# target to preprocess a source file
sdl/endian.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/sdl/endian.c.i
.PHONY : sdl/endian.c.i

sdl/endian.s: sdl/endian.c.s
.PHONY : sdl/endian.s

# target to generate assembly for a file
sdl/endian.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/sdl/endian.c.s
.PHONY : sdl/endian.c.s

sdl/event.o: sdl/event.c.o
.PHONY : sdl/event.o

# target to build an object file
sdl/event.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/sdl/event.c.o
.PHONY : sdl/event.c.o

sdl/event.i: sdl/event.c.i
.PHONY : sdl/event.i

# target to preprocess a source file
sdl/event.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/sdl/event.c.i
.PHONY : sdl/event.c.i

sdl/event.s: sdl/event.c.s
.PHONY : sdl/event.s

# target to generate assembly for a file
sdl/event.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/sdl/event.c.s
.PHONY : sdl/event.c.s

sdl/file.o: sdl/file.c.o
.PHONY : sdl/file.o

# target to build an object file
sdl/file.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/sdl/file.c.o
.PHONY : sdl/file.c.o

sdl/file.i: sdl/file.c.i
.PHONY : sdl/file.i

# target to preprocess a source file
sdl/file.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/sdl/file.c.i
.PHONY : sdl/file.c.i

sdl/file.s: sdl/file.c.s
.PHONY : sdl/file.s

# target to generate assembly for a file
sdl/file.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/sdl/file.c.s
.PHONY : sdl/file.c.s

sdl/video.o: sdl/video.c.o
.PHONY : sdl/video.o

# target to build an object file
sdl/video.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/sdl/video.c.o
.PHONY : sdl/video.c.o

sdl/video.i: sdl/video.c.i
.PHONY : sdl/video.i

# target to preprocess a source file
sdl/video.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/sdl/video.c.i
.PHONY : sdl/video.c.i

sdl/video.s: sdl/video.c.s
.PHONY : sdl/video.s

# target to generate assembly for a file
sdl/video.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/sdl/video.c.s
.PHONY : sdl/video.c.s

video/glfunc.o: video/glfunc.c.o
.PHONY : video/glfunc.o

# target to build an object file
video/glfunc.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/video/glfunc.c.o
.PHONY : video/glfunc.c.o

video/glfunc.i: video/glfunc.c.i
.PHONY : video/glfunc.i

# target to preprocess a source file
video/glfunc.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/video/glfunc.c.i
.PHONY : video/glfunc.c.i

video/glfunc.s: video/glfunc.c.s
.PHONY : video/glfunc.s

# target to generate assembly for a file
video/glfunc.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/video/glfunc.c.s
.PHONY : video/glfunc.c.s

video/opengl.o: video/opengl.c.o
.PHONY : video/opengl.o

# target to build an object file
video/opengl.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/video/opengl.c.o
.PHONY : video/opengl.c.o

video/opengl.i: video/opengl.c.i
.PHONY : video/opengl.i

# target to preprocess a source file
video/opengl.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/video/opengl.c.i
.PHONY : video/opengl.c.i

video/opengl.s: video/opengl.c.s
.PHONY : video/opengl.s

# target to generate assembly for a file
video/opengl.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/video/opengl.c.s
.PHONY : video/opengl.c.s

video/text.o: video/text.c.o
.PHONY : video/text.o

# target to build an object file
video/text.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/video/text.c.o
.PHONY : video/text.c.o

video/text.i: video/text.c.i
.PHONY : video/text.i

# target to preprocess a source file
video/text.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/video/text.c.i
.PHONY : video/text.c.i

video/text.s: video/text.c.s
.PHONY : video/text.s

# target to generate assembly for a file
video/text.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/video/text.c.s
.PHONY : video/text.c.s

video/texture.o: video/texture.c.o
.PHONY : video/texture.o

# target to build an object file
video/texture.c.o:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/video/texture.c.o
.PHONY : video/texture.c.o

video/texture.i: video/texture.c.i
.PHONY : video/texture.i

# target to preprocess a source file
video/texture.c.i:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/video/texture.c.i
.PHONY : video/texture.c.i

video/texture.s: video/texture.c.s
.PHONY : video/texture.s

# target to generate assembly for a file
video/texture.c.s:
	$(MAKE) -f CMakeFiles/gish.dir/build.make CMakeFiles/gish.dir/video/texture.c.s
.PHONY : video/texture.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... gish"
	@echo "... rebuild_cache"
	@echo "... audio/audio.o"
	@echo "... audio/audio.i"
	@echo "... audio/audio.s"
	@echo "... game/ai.o"
	@echo "... game/ai.i"
	@echo "... game/ai.s"
	@echo "... game/animation.o"
	@echo "... game/animation.i"
	@echo "... game/animation.s"
	@echo "... game/block.o"
	@echo "... game/block.i"
	@echo "... game/block.s"
	@echo "... game/boss.o"
	@echo "... game/boss.i"
	@echo "... game/boss.s"
	@echo "... game/config.o"
	@echo "... game/config.i"
	@echo "... game/config.s"
	@echo "... game/credits.o"
	@echo "... game/credits.i"
	@echo "... game/credits.s"
	@echo "... game/custom.o"
	@echo "... game/custom.i"
	@echo "... game/custom.s"
	@echo "... game/damage.o"
	@echo "... game/damage.i"
	@echo "... game/damage.s"
	@echo "... game/debug.o"
	@echo "... game/debug.i"
	@echo "... game/debug.s"
	@echo "... game/editor.o"
	@echo "... game/editor.i"
	@echo "... game/editor.s"
	@echo "... game/game.o"
	@echo "... game/game.i"
	@echo "... game/game.s"
	@echo "... game/gameaudio.o"
	@echo "... game/gameaudio.i"
	@echo "... game/gameaudio.s"
	@echo "... game/gamemenu.o"
	@echo "... game/gamemenu.i"
	@echo "... game/gamemenu.s"
	@echo "... game/gameobject.o"
	@echo "... game/gameobject.i"
	@echo "... game/gameobject.s"
	@echo "... game/gametexture.o"
	@echo "... game/gametexture.i"
	@echo "... game/gametexture.s"
	@echo "... game/high.o"
	@echo "... game/high.i"
	@echo "... game/high.s"
	@echo "... game/level.o"
	@echo "... game/level.i"
	@echo "... game/level.s"
	@echo "... game/lighting.o"
	@echo "... game/lighting.i"
	@echo "... game/lighting.s"
	@echo "... game/logic.o"
	@echo "... game/logic.i"
	@echo "... game/logic.s"
	@echo "... game/mainmenu.o"
	@echo "... game/mainmenu.i"
	@echo "... game/mainmenu.s"
	@echo "... game/mappack.o"
	@echo "... game/mappack.i"
	@echo "... game/mappack.s"
	@echo "... game/music.o"
	@echo "... game/music.i"
	@echo "... game/music.s"
	@echo "... game/objedit.o"
	@echo "... game/objedit.i"
	@echo "... game/objedit.s"
	@echo "... game/objfunc.o"
	@echo "... game/objfunc.i"
	@echo "... game/objfunc.s"
	@echo "... game/options.o"
	@echo "... game/options.i"
	@echo "... game/options.s"
	@echo "... game/physics.o"
	@echo "... game/physics.i"
	@echo "... game/physics.s"
	@echo "... game/player.o"
	@echo "... game/player.i"
	@echo "... game/player.s"
	@echo "... game/prerender.o"
	@echo "... game/prerender.i"
	@echo "... game/prerender.s"
	@echo "... game/random.o"
	@echo "... game/random.i"
	@echo "... game/random.s"
	@echo "... game/record.o"
	@echo "... game/record.i"
	@echo "... game/record.s"
	@echo "... game/render.o"
	@echo "... game/render.i"
	@echo "... game/render.s"
	@echo "... game/replay.o"
	@echo "... game/replay.i"
	@echo "... game/replay.s"
	@echo "... game/ropeedit.o"
	@echo "... game/ropeedit.i"
	@echo "... game/ropeedit.s"
	@echo "... game/setup.o"
	@echo "... game/setup.i"
	@echo "... game/setup.s"
	@echo "... game/socket.o"
	@echo "... game/socket.i"
	@echo "... game/socket.s"
	@echo "... game/sprite.o"
	@echo "... game/sprite.i"
	@echo "... game/sprite.s"
	@echo "... game/vsmode.o"
	@echo "... game/vsmode.i"
	@echo "... game/vsmode.s"
	@echo "... input/joystick.o"
	@echo "... input/joystick.i"
	@echo "... input/joystick.s"
	@echo "... input/keyboard.o"
	@echo "... input/keyboard.i"
	@echo "... input/keyboard.s"
	@echo "... input/mouse.o"
	@echo "... input/mouse.i"
	@echo "... input/mouse.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... math/intersec.o"
	@echo "... math/intersec.i"
	@echo "... math/intersec.s"
	@echo "... math/vector.o"
	@echo "... math/vector.i"
	@echo "... math/vector.s"
	@echo "... menu/menu.o"
	@echo "... menu/menu.i"
	@echo "... menu/menu.s"
	@echo "... parser/parser.o"
	@echo "... parser/parser.i"
	@echo "... parser/parser.s"
	@echo "... physics/bond.o"
	@echo "... physics/bond.i"
	@echo "... physics/bond.s"
	@echo "... physics/object.o"
	@echo "... physics/object.i"
	@echo "... physics/object.s"
	@echo "... physics/particle.o"
	@echo "... physics/particle.i"
	@echo "... physics/particle.s"
	@echo "... sdl/endian.o"
	@echo "... sdl/endian.i"
	@echo "... sdl/endian.s"
	@echo "... sdl/event.o"
	@echo "... sdl/event.i"
	@echo "... sdl/event.s"
	@echo "... sdl/file.o"
	@echo "... sdl/file.i"
	@echo "... sdl/file.s"
	@echo "... sdl/video.o"
	@echo "... sdl/video.i"
	@echo "... sdl/video.s"
	@echo "... video/glfunc.o"
	@echo "... video/glfunc.i"
	@echo "... video/glfunc.s"
	@echo "... video/opengl.o"
	@echo "... video/opengl.i"
	@echo "... video/opengl.s"
	@echo "... video/text.o"
	@echo "... video/text.i"
	@echo "... video/text.s"
	@echo "... video/texture.o"
	@echo "... video/texture.i"
	@echo "... video/texture.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

